### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by alerque** [jonathanzong/proposed-punctuation#2]
Neither this repository nor the website seems to specify a license for this font file. Could I suggest that it be explicitly marked as [OFL](http://scripts.sil.org/OFL)? I just [packaged this for Arch Linux](https://aur.archlinux.org/packages/ttf-bazin-proposed-punctuation/) and it works left blank, it is not technically valid to have an installer that doesn't identify the license.

**Comment by jonathanzong** [comment]
Great suggestion. I added a LICENSE file to the top level of the repo and added a note on the website. Thanks!
